user = input(str("Please enter a number from 1 - 6"))

if user == "1":
  print("ooooooooooo")
  print("o         o")
  print("o         o")
  print("o    #    o")
  print("o         o")
  print("o         o")
  print("ooooooooooo")
elif user == "2":
  print("oooooooooooo") 
  print("o          o")
  print("o  #       o")
  print("o          o")
  print("o       #  o")
  print("o          o")
  print("oooooooooooo")
elif user == "3":
  print("oooooooooooo")
  print("o          o")
  print("o  #       o")
  print("o    #     o")
  print("o       #  o")
  print("o          o") 
  print("oooooooooooo")
elif user == "4":
  print("oooooooooooo")
  print("o          o")
  print("o  #    #  o")
  print("o          o")
  print("o  #    #  o")
  print("o          o")
  print("oooooooooooo")
elif user == "5":
  print("ooooooooooooo")
  print("o           o")
  print("o  #     #  o")
  print("o     #     o")
  print("o  #     #  o")
  print("o           o")
  print("ooooooooooooo")
elif user == "6":
  print("ooooooooooooo")
  print("o           o")
  print("o  #  #  #  o")
  print("o           o")
  print("o  #  #  #  o")
  print("o           o")
  print("ooooooooooooo")
else:
  print("The number is not from 1 to 6. Try again.")
