Length = float(input("Please enter the length of the fish tank "))
Height = float(input("Please enter the height of the fish tank "))
Depth = float(input("Please enter the depth of the fish tank "))
Volume = print(Length * Height * Depth)
Gallons = print("This unit converted to gallons is", Length * Height * Depth / 10000)
